server:
  port: 6003
spring:
  cloud:
    nacos:
      discovery:
        ip: 172.18.192.85
        port: ${server.port}
  application:
    name: zxs-cloud-school
mqtt:
  username: conversion
  password: conversion
  #  password: password
  #  host-url: tcp://172.18.184.237:61613	  #你自己服务器的地址和端口，这个需要改
  host-url: tcp://172.18.192.191:1883	  #你自己服务器的地址和端口，这个需要改
#  host-url: tcp://172.18.192.186:1883	  #你自己服务器的地址和端口，这个需要改
  #  host-url: tcp://172.18.184.210:1883	  #你自己服务器的地址和端口，这个需要改

  clientID: 17218186conversion	# 这个改不改随意，但不同的客户端肯定不能一样
  default-topic: conversion			# 默认主题
  timeout: 100
  keepalive: 30

mqttTopic:
  topic:
    base:
      down:
        visitorInfo:
          param:
            linktype: 1
            retained: false
            timeout: 60
          visitor:
            list: /visit/list
            add: /visit/add
            update: /visit/update
            del: /visit/del