server:
  #微服务端口
  port: 7001
spring:
  cloud:
    nacos:
      discovery:
        ip: 172.18.192.85
        port: ${server.port}
  application:
    name: jeecg-system
feign:
  client:
    config:
      default:
        connectTimeout: 200000
        readTimeout: 200000